
import { AttrMinMax } from "types.slint";

export global SystemInfo {
    in-out property <bool> asus_armoury_loaded: false;
    in-out property <bool> has_dgpu: true;
    in-out property <bool> has_igpu: false;
    in-out property <string> cpu_name: "";
    in-out property <string> igpu_name: "";
    in-out property <string> dgpu_name: "";
    in-out property <string> product_name: "";
}

export global TelemetryData {
    in-out property <int> battery_health: -1;
    in-out property <float> battery_power_consumption: -1.0;
    in-out property <string> battery_status: "Unknown";
    in-out property <string> battery_time_estimate: "";
    
    in-out property <float> cpu_temp_val: -1.0;
    in-out property <float> gpu_temp_val: -1.0;
    in-out property <float> igpu_temp_val: -1.0;
    
    in-out property <float> cpu_usage_val: -1.0;
    in-out property <float> gpu_usage_val: -1.0;
    in-out property <float> igpu_usage_val: -1.0;
    in-out property <float> ram_usage_val: -1.0;
    
    in-out property <float> cpu_freq_mhz: -1.0;
    in-out property <float> gpu_freq_mhz: -1.0;
    
    in-out property <int> cpu_fan_rpm: -1;
    in-out property <int> gpu_fan_rpm: -1;
    in-out property <int> mid_fan_rpm: -1;
    
    in-out property <bool> dgpu_suspended: false;
}

export global PowerData {
    in-out property <AttrMinMax> ppt_pl1_spl: { min: 0, max: 100, current: 20 };
    callback cb_ppt_pl1_spl(int);
    callback cb_default_ppt_pl1_spl();

    in-out property <AttrMinMax> ppt_pl2_sppt: { min: 0, max: 100, current: 20 };
    callback cb_ppt_pl2_sppt(int);
    callback cb_default_ppt_pl2_sppt();

    in-out property <AttrMinMax> ppt_pl3_fppt: { min: 0, max: 100, current: 20 };
    callback cb_ppt_pl3_fppt(int);
    callback cb_default_ppt_pl3_fppt();

    in-out property <AttrMinMax> ppt_fppt: { min: 0, max: 100, current: 20 };
    callback cb_ppt_fppt(int);
    callback cb_default_ppt_fppt();

    in-out property <AttrMinMax> ppt_apu_sppt: { min: 0, max: 100, current: 20 };
    callback cb_ppt_apu_sppt(int);
    callback cb_default_ppt_apu_sppt();

    in-out property <AttrMinMax> ppt_platform_sppt: { min: 0, max: 100, current: 20 };
    callback cb_ppt_platform_sppt(int);
    callback cb_default_ppt_platform_sppt();

    in-out property <AttrMinMax> nv_dynamic_boost: { min: 0, max: 30, current: 5 };
    callback cb_nv_dynamic_boost(int);
    callback cb_default_nv_dynamic_boost();

    in-out property <AttrMinMax> nv_tgp: { min: 0, max: 175, current: 80 };
    callback cb_nv_tgp(int);
    callback cb_default_nv_tgp();

    in-out property <AttrMinMax> nv_temp_target: { min: 0, max: 80, current: 75 };
    callback cb_nv_temp_target(int);
    callback cb_default_nv_temp_target();

    in-out property <bool> enable_ppt_group: false;
    callback cb_enable_ppt_group(bool);

    in-out property <bool> ppt_enabled_available;
    in-out property <bool> ppt_enabled;
    callback cb_ppt_enabled(bool);

    in-out property <int> platform_profile: 0;
    in-out property <[string]> platform_profile_choices: [@tr("Balanced"), @tr("Performance"), @tr("Quiet"), @tr("LowPower")];
    in-out property <[int]> platform_profile_indexes: [0, 1, 2, 3];
    callback cb_platform_profile(int);

    in-out property <[string]> energy_performance_choices: [
        @tr("Default"),
        @tr("Performance"),
        @tr("BalancePerformance"),
        @tr("BalancePower"),
        @tr("Power")
    ];
    in-out property <int> profile_balanced_epp: 0;
    callback cb_profile_balanced_epp(int);
    in-out property <int> profile_performance_epp: 0;
    callback cb_profile_performance_epp(int);
    in-out property <int> profile_quiet_epp: 0;
    callback cb_profile_quiet_epp(int);
    in-out property <bool> platform_profile_linked_epp: true;
    callback cb_platform_profile_linked_epp(bool);

    in-out property <int> platform_profile_on_ac: 0;
    callback cb_platform_profile_on_ac(int);
    in-out property <bool> change_platform_profile_on_ac: true;
    callback cb_change_platform_profile_on_ac(bool);

    in-out property <int> platform_profile_on_battery: 0;
    callback cb_platform_profile_on_battery(int);
    in-out property <bool> change_platform_profile_on_battery: true;
    callback cb_change_platform_profile_on_battery(bool);
}

export global DeviceData {
    in-out property <bool> charge_control_enabled: true;
    in-out property <float> charge_control_end_threshold: 30;
    callback cb_charge_control_end_threshold(int);

    in-out property <int> panel_overdrive;
    callback cb_panel_overdrive(int);

    in-out property <int> boot_sound;
    callback cb_boot_sound(int);

    in-out property <int> screen_auto_brightness;
    callback cb_screen_auto_brightness(int);

    in-out property <int> mcu_powersave;
    callback cb_mcu_powersave(int);

    in-out property <int> mini_led_mode;
    callback cb_mini_led_mode(int);
    in-out property <[string]> mini_led_mode_choices: [@tr("Off"), @tr("Multi-zone"), @tr("Multi-zone Strong")];
    in-out property <[string]> mini_led_choices_onoff: [@tr("Off"), @tr("Multi-zone")];
    in-out property <[string]> mini_led_choices_modes: [@tr("Off"), @tr("Multi-zone"), @tr("Multi-zone Strong")];

    in-out property <float> screenpad_gamma;
    callback cb_screenpad_gamma(float);
    in-out property <int> screenpad_brightness: 50;
    callback cb_screenpad_brightness(int);
    in-out property <bool> screenpad_sync_with_primary: false;
    callback cb_screenpad_sync_with_primary(bool);
}
